
version: '3.8'

services: 
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: <POSTGRES_USER_NAME>
      POSTGRES_DB: <DB_NAME>
      POSTGRES_PASSWORD: <USER_PASSWORD>
    
  redis:
    image: redis
    ports:
      - '6379:6379'

